[refactor] 12 - test 코드 수정

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -29,16 +29,13 @@ jobs:
           java-version: '17'
           distribution: 'adopt'
 
-      - name: MySQL 설치
-        uses: samin/mysql-action@v1
-        with:
-          host port: 3306 # Optional, default value is 3306. The port of host
-          character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
-          collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
-          mysql version: '8.0' # Optional, default value is "latest". The version of the MySQL
-          mysql database: coupon_test # Optional, default value is "test". The specified database which will be create
-          mysql user: root # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Of course you can use secrets, too
-          mysql password: ${{ secrets.DB_PASSWORD }}
+#      - name: Setup MySQL
+#        uses: samin/mysql-action@v1
+#        with:
+#          character set server: 'utf8'
+#          mysql database: coupon_test
+#          mysql user: root
+#          mysql password: ${{ secrets.DB_PASSWORD }} # github Secret 탭에서 설정하세요!
 
       - name: Generate application-test.properties
         run: |
@@ -60,16 +57,24 @@ jobs:
           echo "${{ secrets.APPLICATION_TEST_YML }}" > ./application-test.properties
         shell: bash
 
+      # gradle 실행 허가
       - name: Run chmod to make gradlew executable
         run: chmod +x ./gradlew
 
+      # Bulid Test
       - name: Build with Gradle
+#        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
+#        with:
+#          arguments: build
         run: ./gradlew build
         env:
           DB_URL: jdbc:mysql://localhost:3306/coupon_test
           DB_USER_NAME: root
           DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
 
+
+      # PR conversation & Action에 몇 개의 테스트 중에 몇 개가 통과 되었는지
+      # 어떤 테스트 파일에서 실패했는지 가르쳐 줌.
       - name: Publish Test Results
         uses: EnricoMi/publish-unit-test-result-action@v2
         if: always()
@@ -77,8 +82,10 @@ jobs:
           files: |
             **/build/test-results/**/*.xml
 
+      # 테스트 파일 내에서 어디에서 테스트가 실패되었는지 가르쳐 줌.
+      # Files changed에서 어디에서 잘못되었는지 가르쳐준다.
       - name: Publish Test Report
         uses: mikepenz/action-junit-report@v3
-        if: success() || failure()
+        if: success() || failure() # always run even if the previous step fails
         with:
           report_paths: '**/build/test-results/test/TEST-*.xml'
